### ISSUE TITLE
Case study: crab project spreadsheets

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/hackweek-2019#10]
Work to get crab spreadsheets into one master spreadsheet
repo: https://github.com/RobertsLab/project-crab/tree/master/data

---

Good way to learn the "dos" and "don'ts" of creating spreadsheets, and good way to learn how to make non-machine-readable spreadsheets machine-readable - good to know if you end up collaborating with scientists who don't have bioinformatic backgrounds

**Comment by kubu4** [comment]
Re-think "master" sheet. Instead, have separate sheets (e.g. RNA isolations sheet).

**Comment by laurahspencer** [comment]
@grace-ac did you get what you needed for this data-sheet?

**Comment by grace-ac** [comment]
yup! been working on it- will close issue
