### ISSUE TITLE
Update lab Github Repo (ie onboarding..)

### ISSUE THREAD

**Issue by sr320** [RobertsLab/hackweek-2019#11]
example https://www.openscapes.org/blog/2019/06/06/case-study-pinsky-lab/

**Comment by sr320** [comment]
and http://www.avasthilab.org/lab-policies-and-tips/

**Comment by sr320** [comment]
another example https://twitter.com/samuelmehr/status/1139733291899080705?s=12

**Comment by sr320** [comment]
have a look at a proposed student review form... 
https://github.com/RobertsLab/onboarding/blob/master/student_review.md

**Comment by kubu4** [comment]
Minutes for student review form discussion:

- make wording less formal (i.e. intimidating)
- create two similar sheets - one for advisor and one for student to fill out independently

**Comment by kubu4** [comment]
Minutes for onboarding/resources wikis:

- put most info in resources wiki, but link to from onboarding

- List of "deficiencies" to work on compared to Twitter thread: https://twitter.com/samuelmehr/status/1139733291899080705?s=12

- Add grants received to lab website (where? People page?)

**Comment by yaaminiv** [comment]
Information from on boarding repo will be moved to the Resources repo

**Comment by laurahspencer** [comment]
Another suggestion: add a page with links to the directories/files in the "Code" section to a Wiki page. Bonus: on that page, have "DNA", "RNA", "Protein" sections (etc) with links to all protocols pertinent to those types of extractions.

**Comment by laurahspencer** [comment]
Update:  new pages include: 
- [External Communication and Funding](https://github.com/RobertsLab/resources/wiki/External-Communication-&-Funding). Please add any conferences, outreach, and funding opportunities to this page.  If you received a grant/award, please add, and list your name/year received. I think that, as future students use this page, it would be helpful to know who received grants to a) seek advice if possible, and b) know which are "within reach". 

- [Experiment Database](https://github.com/RobertsLab/resources/wiki/Experiment-Database). We will create a spreadsheets somewhere (Google Spreadsheet?) to begin compiling experiment information. On this page I started a list of fields that we can include. Please add / remove fields as needed!  

- [Lab Protocols](https://github.com/RobertsLab/resources/tree/master/protocols).  There is now a page on the resources Wiki that links to the lab protocols, in which there is a readme file listing protocols grouped by DNA/methylation/RNA/protein/misc.   I started adding short blurbs about when each protocol should be used - please add more information where possible. Also, there are a ton of commercial & external protocols. If there are any "Top 10" protocols that aren't listed on the readme file, please add them with a link!

**Comment by sr320** [comment]
I added lab safety docs to resources. and text from onboarding readme to resources wiki

**Comment by sr320** [comment]
OK I think I have migrated everything from onboarding to resources... might need some cleaning up in resources, but I think all content is there and updated.
