### ISSUE TITLE
Assess NAS burden/needs

### ISSUE THREAD

**Issue by sr320** [RobertsLab/hackweek-2019#13]

**Comment by laurahspencer** [comment]
Resolution (?):  

Moving forward 
- All raw sequence data stored on owl. Files/data already on Owl should not be moved from there. 
- Working directories will be on Gannet

**Comment by kubu4** [comment]
@kubu4 - Make directories for Grace and Laura.

**Comment by kubu4** [comment]
@laurahspencer and @grace-ac - Please provide me with desired folder name for Gannett.

**Comment by grace-ac** [comment]
hydatina

**Comment by kubu4** [comment]
@grace-ac - Done! Let me know if any problems pop up.

**Comment by kubu4** [comment]
@laurahspencer - Done! Let me know if any problems pop up.
