### ISSUE TITLE
Fastest way to get access to full articles

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/hackweek-2019#16]
Curious how people get access to articles seamlessly while off campus. Looking for the fastest way, i.e. not having to go through the UW library website.

**Comment by sr320** [comment]
I use proxy bookmarklet
http://www.lib.washington.edu/help/connect/tools

**Comment by yaaminiv** [comment]
I also use the proxy bookmarklet!

**Comment by yaaminiv** [comment]
I also use the proxy bookmarklet!
