### ISSUE TITLE
T-shirt/Sweatshirt design

### ISSUE THREAD

**Issue by sr320** [RobertsLab/hackweek-2019#6]
As was pointed out, nothing can get done without an issue so here is one for our new apparel line.

Post designs below

**Comment by yaaminiv** [comment]
@kubu4 Our logo has a "fish" in it, so I figured I should add some!

**Comment by laurahspencer** [comment]
By Friday, August 2nd 2019: 
 - People submit options for tshirt designs based off Yaamini's sketch above
 - Try to use graphics pulled from web for species 
 - Design intended to be on front of shirt/sweatshirt, simple

**Comment by sr320** [comment]
![tshirt 002](https://user-images.githubusercontent.com/4442039/62180271-4a577f00-b304-11e9-8e06-574e50562ed5.jpeg)

**Comment by grace-ac** [comment]
One option is that customink.com has a lot of customizable options and also have their own animal art pics. I had to add the oysters and geoduck on my own, but everything else is on there! 

You can customize shirt color, font color, font size, image color and size, rotation of images and text

Here's a link to the one I made real quick... the DNA is kind of intense, I know

 https://www.customink.com/ndx/?cid=rcf0-00bx-hdxr&oe=33673546-f76b0&pc=HL-173485&utm_campaign=hotlink_cab_201712&utm_content=viewinlab&utm_medium=email&utm_source=hotlink#/welcomeBack

**Comment by laurahspencer** [comment]
@yaaminiv updated design w/o DNA 

https://www.customink.com/designs/nodna/rfj0-00bx-mend/share?pc=EMAIL-40778&utm_campaign=shared%20design&utm_source=share%20link&utm_medium=shared%20design&utm_content=shared%20desktop

**Comment by yaaminiv** [comment]
Added 2 different DNA molecules. I think some stuff needs to be shifted around, but I don't have the vision to do that:

https://www.customink.com/designs/nodna/rfj0-00bx-mend/share?pc=EMAIL-40778&utm_campaign=shared%20design&utm_source=share%20link&utm_medium=shared%20design&utm_content=shared%20desktop

**Comment by laurahspencer** [comment]
Update shirt  design - can continue to  customize a bit: https://www.customink.com/designs/withdna/rfj0-00by-x1uu/share?pc=EMAIL-40778&utm_campaign=shared%20design&utm_source=share%20link&utm_medium=shared%20design&utm_content=shared%20desktop

**Comment by grace-ac** [comment]
re-aligned some things to try to get it a bit more centered:   
https://www.customink.com/designs/withdna/rfj0-00by-x1uu/share?pc=EMAIL-40778&utm_campaign=shared%20design&utm_source=share%20link&utm_medium=shared%20design&utm_content=shared%20desktop

**Comment by laurahspencer** [comment]
Me too :)  I also played around with the t-shirt brand to see prices, etc. I personally prefer a triblend (softer), but we can probably order a couple types of shirts if needed. Currently ~20/shirt. 

What about the font? 

https://www.customink.com/designs/withdna/rfj0-00by-x1uu/share?pc=EMAIL-40778&utm_campaign=shared%20design&utm_source=share%20link&utm_medium=shared%20design&utm_content=shared%20desktop

**Comment by yaaminiv** [comment]
I think the front looks great! I like the triblend shirts too. Any color people would rather wear? Personally think the grey looks a little bland but a neutral color would be nice/more professional looking.

**Comment by laurahspencer** [comment]
I'm happy with any color - my favorite is "Tri-Coffee". Purple would be UW-y. Dark blue is nice.
If we go with a lighter color then we probably want the logo to be dark

**Comment by yaaminiv** [comment]
My only veto is the Tri-Coffee (too close to my skin tone) :grimacing: I like the dark blue and green.

**Comment by laurahspencer** [comment]
My final vote: dark blue

**Comment by grace-ac** [comment]
I like everything EXCEPT the purple (It's very similar to my SAFS nautilus shirt) and the oatmeal

everything else is good with me
